name: compare_representations
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.4
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.33
  - nss=3.74
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - packaging=21.3
  - pcre=8.45
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - toml=0.10.2
  - typing_extensions=4.3.0
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - brotlipy==0.7.0
    - certifi==2022.6.15
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - cryptography==37.0.1
    - future==0.18.2
    - kiwisolver==1.4.2
    - latexcodec==2.0.1
    - matplotlib==3.5.1
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - monty==2022.4.26
    - mpmath==1.2.1
    - networkx==2.8.5
    - numpy==1.22.4
    - palettable==3.3.0
    - pandas==1.4.3
    - pillow==9.2.0
    - pip==22.1.2
    - plotly==5.10.0
    - ply==3.11
    - pybtex==0.24.0
    - pymatgen==2022.7.25
    - pyqt5-sip==12.11.0
    - pysocks==1.7.1
    - pytz==2022.2.1
    - pyyaml==6.0
    - requests==2.28.1
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.6
    - scipy==1.7.3
    - setuptools==61.2.0
    - sip==6.6.2
    - spglib==1.16.5
    - sympy==1.10.1
    - tabulate==0.8.10
    - tenacity==8.0.1
    - torch==1.12.1
    - torchvision==0.13.1
    - tornado==6.1
    - tqdm==4.64.0
    - typing-extensions==4.3.0
    - uncertainties==3.1.7
    - urllib3==1.26.11
